DROP SCHEMA IF EXISTS public;

CREATE SCHEMA IF NOT EXISTS gen AUTHORIZATION "statsdb-dev";
CREATE SCHEMA IF NOT EXISTS test AUTHORIZATION "statsdb-dev";
CREATE SCHEMA IF NOT EXISTS dev AUTHORIZATION "statsdb-dev";
CREATE SCHEMA IF NOT EXISTS prod AUTHORIZATION statsdb;