CREATE CONSTRAINT ON (a:Artist) ASSERT a.name IS UNIQUE
CREATE CONSTRAINT ON (y:Year) ASSERT y.value IS UNIQUE
CREATE CONSTRAINT ON (d:Decade) ASSERT d.value IS UNIQUE
CREATE CONSTRAINT ON (c:Country) ASSERT c.code IS UNIQUE
CREATE CONSTRAINT ON (g:Genre) ASSERT g.name IS UNIQUE

// Enterprise Feature
// CREATE CONSTRAINT ON ()-[playCount:HAS_BEEN_PLAYED_IN]-() ASSERT exists(playCount.value)
