Insert into artists (ID,NAME) values ('459','"Weird Al" Yankovic');
Insert into artists (ID,NAME) values ('2','3 Doors Down');
Insert into artists (ID,NAME) values ('237','A-ha');
Insert into artists (ID,NAME) values ('795','AC/DC');
Insert into artists (ID,NAME) values ('591','AFI');
Insert into artists (ID,NAME) values ('1046','Abba');
Insert into artists (ID,NAME) values ('6900','Adel Tawil');
Insert into artists (ID,NAME) values ('430','Adorned Brood');
Insert into artists (ID,NAME) values ('4','Aerosmith');
Insert into artists (ID,NAME) values ('150','Alanis Morissette');
Insert into artists (ID,NAME) values ('6793','Alexander Marcus');
Insert into artists (ID,NAME) values ('334','Alice Cooper');
Insert into artists (ID,NAME) values ('4605','Alice in Chains');
Insert into artists (ID,NAME) values ('3529','Alicia Keys');
Insert into artists (ID,NAME) values ('1023','America');
Insert into artists (ID,NAME) values ('4180','Amy MacDonald');
Insert into artists (ID,NAME) values ('1199','Amy Winehouse');
Insert into artists (ID,NAME) values ('557','Anathema');
Insert into artists (ID,NAME) values ('3106','Angelo Badalamenti');
Insert into artists (ID,NAME) values ('2084','Anna Katharina');
Insert into artists (ID,NAME) values ('7958','Anna Kendrick');
Insert into artists (ID,NAME) values ('7998','Antilopen Gang');
Insert into artists (ID,NAME) values ('735','Apocalyptica');
Insert into artists (ID,NAME) values ('170','At The Gates');
Insert into artists (ID,NAME) values ('187','Bad Company');
Insert into artists (ID,NAME) values ('441','Bad Religion');
Insert into artists (ID,NAME) values ('101','Bananafishbones');
Insert into artists (ID,NAME) values ('353','Bandits');
Insert into artists (ID,NAME) values ('7603','Baron');
Insert into artists (ID,NAME) values ('7150','Battleme');
Insert into artists (ID,NAME) values ('438','Bear McCreary');
Insert into artists (ID,NAME) values ('1528','Beck');
Insert into artists (ID,NAME) values ('6','Bela B.');
Insert into artists (ID,NAME) values ('7145','Billy Valentine');
Insert into artists (ID,NAME) values ('536','Björk');
Insert into artists (ID,NAME) values ('7','Black Sabbath');
Insert into artists (ID,NAME) values ('74','Blank & Jones');
Insert into artists (ID,NAME) values ('4064','Blur');
Insert into artists (ID,NAME) values ('632','Bob Dylan');
Insert into artists (ID,NAME) values ('854','Bob Marley');
Insert into artists (ID,NAME) values ('533','Bob Marley & The Wailers');
Insert into artists (ID,NAME) values ('7698','Body Count');
Insert into artists (ID,NAME) values ('8','Bon Jovi');
Insert into artists (ID,NAME) values ('9','Boston');
Insert into artists (ID,NAME) values ('3115','Brad Fiedel');
Insert into artists (ID,NAME) values ('11','Brian May');
Insert into artists (ID,NAME) values ('5085','Bruce Hornsby');
Insert into artists (ID,NAME) values ('219','Bruce Springsteen');
Insert into artists (ID,NAME) values ('125','Bryan Adams');
Insert into artists (ID,NAME) values ('472','Buffy The Vampire Slayer Cast');
Insert into artists (ID,NAME) values ('7541','Bundesjugendorchester unter Leitung von Alexander Shelley');
Insert into artists (ID,NAME) values ('6435','Callejon');
Insert into artists (ID,NAME) values ('263','Carcass');
Insert into artists (ID,NAME) values ('191','Cat Stevens');
Insert into artists (ID,NAME) values ('4764','Chairlift');
Insert into artists (ID,NAME) values ('422','Chicane');
Insert into artists (ID,NAME) values ('669','Children Of Bodom');
Insert into artists (ID,NAME) values ('622','Chingon');
Insert into artists (ID,NAME) values ('922','Coldplay');
Insert into artists (ID,NAME) values ('13','Colin Hay');
Insert into artists (ID,NAME) values ('1193','Corrosion Of Conformity');
Insert into artists (ID,NAME) values ('7026','Cryssis');
Insert into artists (ID,NAME) values ('7172','Curtis Stigers');
Insert into artists (ID,NAME) values ('870','D:A:D');
Insert into artists (ID,NAME) values ('6447','DAS DA Kinder- und Jugendtheater');
Insert into artists (ID,NAME) values ('3510','Daft Punk');
Insert into artists (ID,NAME) values ('2880','Daniel Licht');
Insert into artists (ID,NAME) values ('5381','Das Pack');
Insert into artists (ID,NAME) values ('7540','Das Sinfonieorchester der Robert Schumann Hochschule & Die Toten Hosen');
Insert into artists (ID,NAME) values ('6772','Dave Porter');
Insert into artists (ID,NAME) values ('509','David Arnold');
Insert into artists (ID,NAME) values ('14','David Bowie');
Insert into artists (ID,NAME) values ('15','David Hasselhoff');
Insert into artists (ID,NAME) values ('3228','David Newman');
Insert into artists (ID,NAME) values ('3349','Dead Kennedys');
Insert into artists (ID,NAME) values ('107','Death');
Insert into artists (ID,NAME) values ('124','Deep Purple');
Insert into artists (ID,NAME) values ('1105','Def Leppard');
Insert into artists (ID,NAME) values ('7720','Deine Freunde');
Insert into artists (ID,NAME) values ('141','Depeche Mode');
Insert into artists (ID,NAME) values ('16','Depp Jones');
Insert into artists (ID,NAME) values ('476','Derek Sherinian');
Insert into artists (ID,NAME) values ('75','Dido');
Insert into artists (ID,NAME) values ('78','Die Apokalyptischen Reiter');
Insert into artists (ID,NAME) values ('382','Die Fantastischen Vier');
Insert into artists (ID,NAME) values ('6975','Die Feisten');
Insert into artists (ID,NAME) values ('20','Die Toten Hosen');
Insert into artists (ID,NAME) values ('17','Die Ärzte');
Insert into artists (ID,NAME) values ('21','Dire Straits');
Insert into artists (ID,NAME) values ('475','Disturbed');
Insert into artists (ID,NAME) values ('1670','Don Davis');
Insert into artists (ID,NAME) values ('22','Donots');
Insert into artists (ID,NAME) values ('23','Dream Theater');
Insert into artists (ID,NAME) values ('586','Dropkick Murphys');
Insert into artists (ID,NAME) values ('8339','Ednaswap');
Insert into artists (ID,NAME) values ('804','Eels');
Insert into artists (ID,NAME) values ('68','Electric Six');
Insert into artists (ID,NAME) values ('194','Elton John');
Insert into artists (ID,NAME) values ('231','Elvis Presley');
Insert into artists (ID,NAME) values ('326','Eminem');
Insert into artists (ID,NAME) values ('27','Eric Fish');
Insert into artists (ID,NAME) values ('4633','Eric St-Laurent, Thomy Jordy und Thomas Alkier feat. Helge Schneider');
Insert into artists (ID,NAME) values ('6872','Erik Cohen');
Insert into artists (ID,NAME) values ('335','Europe');
Insert into artists (ID,NAME) values ('2489','Evergreen Terrace');
Insert into artists (ID,NAME) values ('411','Faith No More');
Insert into artists (ID,NAME) values ('184','Faithless');
Insert into artists (ID,NAME) values ('197','Falco');
Insert into artists (ID,NAME) values ('79','Farin Urlaub');
Insert into artists (ID,NAME) values ('128','Farin Urlaub Racing Team');
Insert into artists (ID,NAME) values ('3615','Fatboy Slim');
Insert into artists (ID,NAME) values ('7480','Feine Sahne Fischfilet');
Insert into artists (ID,NAME) values ('77','Ferris MC');
Insert into artists (ID,NAME) values ('29','Fettes Brot');
Insert into artists (ID,NAME) values ('5387','Five Finger Death Punch');
Insert into artists (ID,NAME) values ('308','Foo Fighters');
Insert into artists (ID,NAME) values ('1350','Frank Sinatra');
Insert into artists (ID,NAME) values ('142','Frank Zappa');
Insert into artists (ID,NAME) values ('317','Frankie Goes To Hollywood');
Insert into artists (ID,NAME) values ('67','Freddie Mercury');
Insert into artists (ID,NAME) values ('6347','Freddie Mercury & Montserrat Caballé');
Insert into artists (ID,NAME) values ('369','Free');
Insert into artists (ID,NAME) values ('7566','Fritz Kalkbrenner');
Insert into artists (ID,NAME) values ('30','Fugees');
Insert into artists (ID,NAME) values ('362','Gary Moore');
Insert into artists (ID,NAME) values ('31','Genesis');
Insert into artists (ID,NAME) values ('4760','Glenn Gould');
Insert into artists (ID,NAME) values ('1226','Gorillaz');
Insert into artists (ID,NAME) values ('4837','Gossip');
Insert into artists (ID,NAME) values ('174','Green Day');
Insert into artists (ID,NAME) values ('3227','Greg Edmonson');
Insert into artists (ID,NAME) values ('8574','Greta Van Fleet');
Insert into artists (ID,NAME) values ('1067','Grinderman');
Insert into artists (ID,NAME) values ('372','Guano Apes');
Insert into artists (ID,NAME) values ('32','Guns n'' Roses');
Insert into artists (ID,NAME) values ('2289','Gustavo Santaolalla');
Insert into artists (ID,NAME) values ('371','H-Blockx');
Insert into artists (ID,NAME) values ('352','HIM');
Insert into artists (ID,NAME) values ('1263','Hans Zimmer');
Insert into artists (ID,NAME) values ('3583','Hawkwind');
Insert into artists (ID,NAME) values ('406','Hayseed Dixie');
Insert into artists (ID,NAME) values ('6491','Heino');
Insert into artists (ID,NAME) values ('6040','Helge & Hardcore');
Insert into artists (ID,NAME) values ('35','Helge Schneider');
Insert into artists (ID,NAME) values ('3564','Hellsongs');
Insert into artists (ID,NAME) values ('99','Herbert Grönemeyer');
Insert into artists (ID,NAME) values ('7061','Het Brabants Orkest');
Insert into artists (ID,NAME) values ('8008','Hey Satan');
Insert into artists (ID,NAME) values ('94','Hooters');
Insert into artists (ID,NAME) values ('690','House Of Spirits');
Insert into artists (ID,NAME) values ('6721','Héroes del Silencio');
Insert into artists (ID,NAME) values ('5192','Höhner');
Insert into artists (ID,NAME) values ('8024','Ice-T');
Insert into artists (ID,NAME) values ('83','Iced Earth');
Insert into artists (ID,NAME) values ('573','Iggy Pop');
Insert into artists (ID,NAME) values ('273','In Extremo');
Insert into artists (ID,NAME) values ('133','In Flames');
Insert into artists (ID,NAME) values ('789','Incubus');
Insert into artists (ID,NAME) values ('105','Iron Maiden');
Insert into artists (ID,NAME) values ('310','J.B.O.');
Insert into artists (ID,NAME) values ('5024','J.Viewz');
Insert into artists (ID,NAME) values ('4575','Jace Everett');
Insert into artists (ID,NAME) values ('2312','Jamie Cullum');
Insert into artists (ID,NAME) values ('4719','Jamiroquai');
Insert into artists (ID,NAME) values ('1453','Jan Delay');
Insert into artists (ID,NAME) values ('1943','Jean-Michel Jarre');
Insert into artists (ID,NAME) values ('238','Joe Cocker');
Insert into artists (ID,NAME) values ('4273','John Williams');
Insert into artists (ID,NAME) values ('307','Johnny Cash');
Insert into artists (ID,NAME) values ('7181','Joshua James');
Insert into artists (ID,NAME) values ('680','Joss Stone');
Insert into artists (ID,NAME) values ('579','Judas Priest');
Insert into artists (ID,NAME) values ('2533','Justin Timberlake');
Insert into artists (ID,NAME) values ('6605','Kadavar');
Insert into artists (ID,NAME) values ('7036','Kai Lüftner & Klabauterband');
Insert into artists (ID,NAME) values ('7551','Kaleo');
Insert into artists (ID,NAME) values ('7342','Kamasi Washington');
Insert into artists (ID,NAME) values ('7152','Katey Sagal');
Insert into artists (ID,NAME) values ('762','Ken Freeman');
Insert into artists (ID,NAME) values ('3640','Kerry Ellis');
Insert into artists (ID,NAME) values ('1764','Kettcar');
Insert into artists (ID,NAME) values ('3397','Kid Rock');
Insert into artists (ID,NAME) values ('6621','Kikaninchen');
Insert into artists (ID,NAME) values ('393','King Køng');
Insert into artists (ID,NAME) values ('311','Kiss');
Insert into artists (ID,NAME) values ('6057','Klaus Doldinger');
Insert into artists (ID,NAME) values ('417','Knorkator');
Insert into artists (ID,NAME) values ('428','Korn');
Insert into artists (ID,NAME) values ('122','Koroded');
Insert into artists (ID,NAME) values ('6242','Kraftklub');
Insert into artists (ID,NAME) values ('267','Kreator');
Insert into artists (ID,NAME) values ('4911','La Roux');
Insert into artists (ID,NAME) values ('4595','LaBrassBanda');
Insert into artists (ID,NAME) values ('5479','Lady GaGa');
Insert into artists (ID,NAME) values ('69','Laibach');
Insert into artists (ID,NAME) values ('6078','Lana Del Rey');
Insert into artists (ID,NAME) values ('5857','Laternen-Joe');
Insert into artists (ID,NAME) values ('39','Led Zeppelin');
Insert into artists (ID,NAME) values ('3626','Lemmy');
Insert into artists (ID,NAME) values ('40','Lemonbabies');
Insert into artists (ID,NAME) values ('5415','Lena');
Insert into artists (ID,NAME) values ('627','Leningrad Cowboys');
Insert into artists (ID,NAME) values ('3347','Lenny Kravitz');
Insert into artists (ID,NAME) values ('510','Leonard Cohen');
Insert into artists (ID,NAME) values ('6683','Lingua Mortis Orchestra');
Insert into artists (ID,NAME) values ('109','Linkin Park');
Insert into artists (ID,NAME) values ('6357','London Symphony Orchestra');
Insert into artists (ID,NAME) values ('2141','Lou Reed');
Insert into artists (ID,NAME) values ('403','Macabre');
Insert into artists (ID,NAME) values ('41','Madness');
Insert into artists (ID,NAME) values ('391','Madonna');
Insert into artists (ID,NAME) values ('1229','Mando Diao');
Insert into artists (ID,NAME) values ('3126','Marco Beltrami');
Insert into artists (ID,NAME) values ('1111','Maria Mena');
Insert into artists (ID,NAME) values ('215','Mariah Carey');
Insert into artists (ID,NAME) values ('5614','Marianne Faithfull');
Insert into artists (ID,NAME) values ('172','Marilyn Manson');
Insert into artists (ID,NAME) values ('8556','Mark Mothersbaugh');
Insert into artists (ID,NAME) values ('7119','Martel');
Insert into artists (ID,NAME) values ('4763','Martin Stadtfeld');
Insert into artists (ID,NAME) values ('521','Massive Attack');
Insert into artists (ID,NAME) values ('626','Me First And The Gimme Gimmes');
Insert into artists (ID,NAME) values ('92','Meat Loaf');
Insert into artists (ID,NAME) values ('7024','Meg''n Jez');
Insert into artists (ID,NAME) values ('116','Megadeth');
Insert into artists (ID,NAME) values ('7575','Melissa Auf der Maur');
Insert into artists (ID,NAME) values ('44','Metallica');
Insert into artists (ID,NAME) values ('214','Michael Jackson');
Insert into artists (ID,NAME) values ('6286','Michael Viner''s Incredible Bongo Band');
Insert into artists (ID,NAME) values ('6901','Milky Chance');
Insert into artists (ID,NAME) values ('5227','Miss Platnum');
Insert into artists (ID,NAME) values ('7358','Mitch Murder');
Insert into artists (ID,NAME) values ('696','Moby');
Insert into artists (ID,NAME) values ('437','Monster Magnet');
Insert into artists (ID,NAME) values ('190','Morrissey');
Insert into artists (ID,NAME) values ('86','Motörhead');
Insert into artists (ID,NAME) values ('1649','Murray Gold');
Insert into artists (ID,NAME) values ('396','Napalm Death');
Insert into artists (ID,NAME) values ('158','Natasha Bedingfield');
Insert into artists (ID,NAME) values ('7210','Neil Young & Crazy Horse');
Insert into artists (ID,NAME) values ('45','Nelly Furtado');
Insert into artists (ID,NAME) values ('801','Nena');
Insert into artists (ID,NAME) values ('46','Nevermore');
Insert into artists (ID,NAME) values ('207','Nick Cave & The Bad Seeds');
Insert into artists (ID,NAME) values ('47','Nickelback');
Insert into artists (ID,NAME) values ('312','Nightwish');
Insert into artists (ID,NAME) values ('791','Nirvana');
Insert into artists (ID,NAME) values ('4875','Noiseaux');
Insert into artists (ID,NAME) values ('644','Oasis');
Insert into artists (ID,NAME) values ('48','Opeth');
Insert into artists (ID,NAME) values ('49','Ozzy Osbourne');
Insert into artists (ID,NAME) values ('165','P!nk');
Insert into artists (ID,NAME) values ('5228','PSP');
Insert into artists (ID,NAME) values ('50','Pantera');
Insert into artists (ID,NAME) values ('3957','Paul Kalkbrenner');
Insert into artists (ID,NAME) values ('108','Paul McCartney');
Insert into artists (ID,NAME) values ('780','Paul Rodgers');
Insert into artists (ID,NAME) values ('673','Paul Simon');
Insert into artists (ID,NAME) values ('3448','Paul van Dyk');
Insert into artists (ID,NAME) values ('200','Pearl Jam');
Insert into artists (ID,NAME) values ('51','Pet Shop Boys');
Insert into artists (ID,NAME) values ('2951','Peter Fox');
Insert into artists (ID,NAME) values ('6894','Pharrell Williams');
Insert into artists (ID,NAME) values ('234','Phil Collins');
Insert into artists (ID,NAME) values ('126','Pink Floyd');
Insert into artists (ID,NAME) values ('3627','Probot');
Insert into artists (ID,NAME) values ('135','Psycho Luna');
Insert into artists (ID,NAME) values ('54','Queen');
Insert into artists (ID,NAME) values ('427','R.E.M.');
Insert into artists (ID,NAME) values ('700','Radiohead');
Insert into artists (ID,NAME) values ('71','Rage');
Insert into artists (ID,NAME) values ('323','Rage Against The Machine');
Insert into artists (ID,NAME) values ('2750','Ramin Djawadi');
Insert into artists (ID,NAME) values ('388','Rammstein');
Insert into artists (ID,NAME) values ('113','Ramones');
Insert into artists (ID,NAME) values ('366','Red Hot Chili Peppers');
Insert into artists (ID,NAME) values ('330','Richard Cheese');
Insert into artists (ID,NAME) values ('2480','Richard Gibbs');
Insert into artists (ID,NAME) values ('6098','Ritter Rost');
Insert into artists (ID,NAME) values ('4545','Rivo Drei');
Insert into artists (ID,NAME) values ('56','Rob Zombie');
Insert into artists (ID,NAME) values ('129','Robbie Williams');
Insert into artists (ID,NAME) values ('2571','Robert Rodriguez');
Insert into artists (ID,NAME) values ('57','Roger Taylor');
Insert into artists (ID,NAME) values ('97','Roxette');
Insert into artists (ID,NAME) values ('636','Roy Black');
Insert into artists (ID,NAME) values ('3858','Run-D.M.C.');
Insert into artists (ID,NAME) values ('397','Samael');
Insert into artists (ID,NAME) values ('127','Santana');
Insert into artists (ID,NAME) values ('58','Schandmaul');
Insert into artists (ID,NAME) values ('59','Schiller');
Insert into artists (ID,NAME) values ('1044','Scissor Sisters');
Insert into artists (ID,NAME) values ('60','Scorpions');
Insert into artists (ID,NAME) values ('5321','Sedlmeir');
Insert into artists (ID,NAME) values ('3512','Seeed');
Insert into artists (ID,NAME) values ('100','Sentenced');
Insert into artists (ID,NAME) values ('4095','Sepultura');
Insert into artists (ID,NAME) values ('3310','Serj Tankian');
Insert into artists (ID,NAME) values ('2959','Sex Pistols');
Insert into artists (ID,NAME) values ('114','Shakira');
Insert into artists (ID,NAME) values ('461','Shirley Bassey');
Insert into artists (ID,NAME) values ('7641','Shuki Levy, Haim Saban & Erika Lane');
Insert into artists (ID,NAME) values ('2127','Sido');
Insert into artists (ID,NAME) values ('3269','Siena Root');
Insert into artists (ID,NAME) values ('663','Silbermond');
Insert into artists (ID,NAME) values ('4975','Simon Phillips');
Insert into artists (ID,NAME) values ('232','Six Feet Under');
Insert into artists (ID,NAME) values ('5012','Slash');
Insert into artists (ID,NAME) values ('4740','Slash''s Snakepit');
Insert into artists (ID,NAME) values ('88','Slayer');
Insert into artists (ID,NAME) values ('828','Slipknot');
Insert into artists (ID,NAME) values ('262','Smoke Blow');
Insert into artists (ID,NAME) values ('3926','Snoop Dogg');
Insert into artists (ID,NAME) values ('6362','Snoop Lion');
Insert into artists (ID,NAME) values ('279','Soft Cell');
Insert into artists (ID,NAME) values ('134','Soilwork');
Insert into artists (ID,NAME) values ('874','Soundgarden');
Insert into artists (ID,NAME) values ('6456','Spiritual Beggars');
Insert into artists (ID,NAME) values ('3045','Stefanie Heinzmann');
Insert into artists (ID,NAME) values ('5439','Stevie Salas');
Insert into artists (ID,NAME) values ('186','Sting');
Insert into artists (ID,NAME) values ('5896','Stumpen, Buzz Dee und Ally');
Insert into artists (ID,NAME) values ('93','Subway To Sally');
Insert into artists (ID,NAME) values ('3677','Such A Surge');
Insert into artists (ID,NAME) values ('6409','Sugarcubes');
Insert into artists (ID,NAME) values ('6898','Suppi Huhn und die Kinderkönige');
Insert into artists (ID,NAME) values ('265','System Of A Down');
Insert into artists (ID,NAME) values ('6696','T.V. Smith');
Insert into artists (ID,NAME) values ('192','Take That');
Insert into artists (ID,NAME) values ('3972','Talking Heads');
Insert into artists (ID,NAME) values ('4557','Tarkan');
Insert into artists (ID,NAME) values ('147','Tears For Fears');
Insert into artists (ID,NAME) values ('123','Tenacious D.');
Insert into artists (ID,NAME) values ('658','The Beatles');
Insert into artists (ID,NAME) values ('818','The Blues Brothers');
Insert into artists (ID,NAME) values ('630','The Clash');
Insert into artists (ID,NAME) values ('156','The Cross');
Insert into artists (ID,NAME) values ('674','The Darkness');
Insert into artists (ID,NAME) values ('7588','The Head Cat');
Insert into artists (ID,NAME) values ('5875','The Jimi Hendrix Experience');
Insert into artists (ID,NAME) values ('309','The Kleptones');
Insert into artists (ID,NAME) values ('5554','The London Philharmonic Orchestra');
Insert into artists (ID,NAME) values ('689','The Offspring');
Insert into artists (ID,NAME) values ('104','The Police');
Insert into artists (ID,NAME) values ('434','The Prodigy');
Insert into artists (ID,NAME) values ('7942','The Queen Extravaganza');
Insert into artists (ID,NAME) values ('8163','The Rezillos');
Insert into artists (ID,NAME) values ('582','The Rolling Stones');
Insert into artists (ID,NAME) values ('2124','The Sisters Of Mercy');
Insert into artists (ID,NAME) values ('763','The Skywalker Symphony Orchestra');
Insert into artists (ID,NAME) values ('381','The Smashing Pumpkins');
Insert into artists (ID,NAME) values ('456','The Twang');
Insert into artists (ID,NAME) values ('6346','The Undertones');
Insert into artists (ID,NAME) values ('7179','The White Buffalo');
Insert into artists (ID,NAME) values ('1464','The White Stripes');
Insert into artists (ID,NAME) values ('379','The Who');
Insert into artists (ID,NAME) values ('815','Therapy?');
Insert into artists (ID,NAME) values ('169','Thomas D.');
Insert into artists (ID,NAME) values ('145','Tim Staffell');
Insert into artists (ID,NAME) values ('209','Tina Turner');
Insert into artists (ID,NAME) values ('143','Tito & Tarantula');
Insert into artists (ID,NAME) values ('5287','Tom Petty And The Heartbreakers');
Insert into artists (ID,NAME) values ('416','Tori Amos');
Insert into artists (ID,NAME) values ('701','Toto');
Insert into artists (ID,NAME) values ('453','Trevor Rabin');
Insert into artists (ID,NAME) values ('6300','Triggerfinger');
Insert into artists (ID,NAME) values ('327','Turbonegro');
Insert into artists (ID,NAME) values ('503','U2');
Insert into artists (ID,NAME) values ('3270','Udo Lindenberg');
Insert into artists (ID,NAME) values ('730','Van Halen');
Insert into artists (ID,NAME) values ('65','Various');
Insert into artists (ID,NAME) values ('660','Venom');
Insert into artists (ID,NAME) values ('939','Ville Valo & Natalia Avelon');
Insert into artists (ID,NAME) values ('5331','WDR 2 Kabarett');
Insert into artists (ID,NAME) values ('66','Whitesnake');
Insert into artists (ID,NAME) values ('819','Wir sind Helden');
Insert into artists (ID,NAME) values ('740','Wizo');
Insert into artists (ID,NAME) values ('1182','Wolfsheim');
Insert into artists (ID,NAME) values ('247','World Downfall');
Insert into artists (ID,NAME) values ('8004','Yoko Shimomura, Isao Abe & Syun Nishigaki');
Insert into artists (ID,NAME) values ('446','ZZ Top');
Insert into artists (ID,NAME) values ('6847','Zaches & Zinnober');
Insert into artists (ID,NAME) values ('6287','¡Más Shake!');
