Insert into genres (ID,NAME) values ('62','Acid Jazz');
Insert into genres (ID,NAME) values ('1','Alternative');
Insert into genres (ID,NAME) values ('80','Alternative Rock');
Insert into genres (ID,NAME) values ('22','Ambient');
Insert into genres (ID,NAME) values ('79','Big Beat');
Insert into genres (ID,NAME) values ('24','Black Metal');
Insert into genres (ID,NAME) values ('2','Blues');
Insert into genres (ID,NAME) values ('3','Blues/R&B');
Insert into genres (ID,NAME) values ('73','BritPop');
Insert into genres (ID,NAME) values ('87','Classic Rock');
Insert into genres (ID,NAME) values ('4','Comedy');
Insert into genres (ID,NAME) values ('31','Country');
Insert into genres (ID,NAME) values ('28','Crossover');
Insert into genres (ID,NAME) values ('63','Dance');
Insert into genres (ID,NAME) values ('21','Death Metal');
Insert into genres (ID,NAME) values ('5','Electronic');
Insert into genres (ID,NAME) values ('6','Folk');
Insert into genres (ID,NAME) values ('88','Folk Rock');
Insert into genres (ID,NAME) values ('81','Funk');
Insert into genres (ID,NAME) values ('92','Funk Rock');
Insert into genres (ID,NAME) values ('29','Gothic Metal');
Insert into genres (ID,NAME) values ('69','Gothic Rock');
Insert into genres (ID,NAME) values ('27','Grindcore');
Insert into genres (ID,NAME) values ('30','Grunge');
Insert into genres (ID,NAME) values ('7','Hard Rock');
Insert into genres (ID,NAME) values ('76','Hardcore Punk');
Insert into genres (ID,NAME) values ('8','Heavy Metal');
Insert into genres (ID,NAME) values ('93','Hip Hop');
Insert into genres (ID,NAME) values ('9','Hip-Hop');
Insert into genres (ID,NAME) values ('82','Horrorcore');
Insert into genres (ID,NAME) values ('40','House');
Insert into genres (ID,NAME) values ('33','Hörbuch & Gesprochene Inhalte');
Insert into genres (ID,NAME) values ('10','Industrial');
Insert into genres (ID,NAME) values ('41','Jazz');
Insert into genres (ID,NAME) values ('25','Klassik');
Insert into genres (ID,NAME) values ('26','Mashup');
Insert into genres (ID,NAME) values ('75','Metalcore');
Insert into genres (ID,NAME) values ('34','Murder Metal');
Insert into genres (ID,NAME) values ('58','Musik für Kinder');
Insert into genres (ID,NAME) values ('23','New Metal');
Insert into genres (ID,NAME) values ('70','New Wave');
Insert into genres (ID,NAME) values ('55','Podcast');
Insert into genres (ID,NAME) values ('11','Pop');
Insert into genres (ID,NAME) values ('12','Progressive Metal');
Insert into genres (ID,NAME) values ('72','Progressive Rock');
Insert into genres (ID,NAME) values ('78','Psychedelic Rock');
Insert into genres (ID,NAME) values ('13','Punk');
Insert into genres (ID,NAME) values ('14','Punk Rock');
Insert into genres (ID,NAME) values ('46','R&B');
Insert into genres (ID,NAME) values ('15','Rap');
Insert into genres (ID,NAME) values ('35','Reggae');
Insert into genres (ID,NAME) values ('16','Rock');
Insert into genres (ID,NAME) values ('85','Rock and roll');
Insert into genres (ID,NAME) values ('90','Rockabilly');
Insert into genres (ID,NAME) values ('17','Schlager');
Insert into genres (ID,NAME) values ('54','Singer/Songwriter');
Insert into genres (ID,NAME) values ('18','Ska');
Insert into genres (ID,NAME) values ('36','Soul');
Insert into genres (ID,NAME) values ('19','Soundtrack');
Insert into genres (ID,NAME) values ('86','Soundtracks');
Insert into genres (ID,NAME) values ('68','Southern Rock');
Insert into genres (ID,NAME) values ('74','Space');
Insert into genres (ID,NAME) values ('32','Swing');
Insert into genres (ID,NAME) values ('66','SynthPop');
Insert into genres (ID,NAME) values ('38','Techno');
Insert into genres (ID,NAME) values ('20','Thrash Metal');
Insert into genres (ID,NAME) values ('77','Trip-Hop');
Insert into genres (ID,NAME) values ('61','Unknown');
